package Modelo;
// Generated 12-abr-2023 12:55:10 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Empleados generated by hbm2java
 */
public class Empleados  implements java.io.Serializable {


     private int numEmpleado;
     private String nombre;
     private String paterno;
     private String materno;
     private String direccion;
     private Long celular;
     private String correo;
     private String sexo;
     private String cargo;
     private Set<Factura> facturas = new HashSet<Factura>(0);

    public Empleados() {
    }

	
    public Empleados(int numEmpleado) {
        this.numEmpleado = numEmpleado;
    }
    public Empleados(int numEmpleado, String nombre, String paterno, String materno, String direccion, Long celular, String correo, String sexo, String cargo, Set<Factura> facturas) {
       this.numEmpleado = numEmpleado;
       this.nombre = nombre;
       this.paterno = paterno;
       this.materno = materno;
       this.direccion = direccion;
       this.celular = celular;
       this.correo = correo;
       this.sexo = sexo;
       this.cargo = cargo;
       this.facturas = facturas;
    }
   
    public int getNumEmpleado() {
        return this.numEmpleado;
    }
    
    public void setNumEmpleado(int numEmpleado) {
        this.numEmpleado = numEmpleado;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getPaterno() {
        return this.paterno;
    }
    
    public void setPaterno(String paterno) {
        this.paterno = paterno;
    }
    public String getMaterno() {
        return this.materno;
    }
    
    public void setMaterno(String materno) {
        this.materno = materno;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Long getCelular() {
        return this.celular;
    }
    
    public void setCelular(Long celular) {
        this.celular = celular;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    public String getCargo() {
        return this.cargo;
    }
    
    public void setCargo(String cargo) {
        this.cargo = cargo;
    }
    public Set<Factura> getFacturas() {
        return this.facturas;
    }
    
    public void setFacturas(Set<Factura> facturas) {
        this.facturas = facturas;
    }




}


