package Modelo;
// Generated 12-abr-2023 12:55:10 by Hibernate Tools 4.3.1


import java.sql.Time;
import java.time.LocalDateTime;
import java.util.Date;

/**
 * Factura generated by hbm2java
 */
public class Factura  implements java.io.Serializable {


     private Integer clave;
     private String rfc;
     private Integer numEmpleado;
     private Integer codigo;
     private Date fechaCompra;
     private Date horaCompra;
     private Double pagoTotal;

    public Factura() {
    }

    public Factura(String rfc, Integer numEmpleado, Integer codigo, Date fechaCompra, Date horaCompra, Double pagoTotal) {
       this.rfc = rfc;
       this.numEmpleado = numEmpleado;
       this.codigo = codigo;
       this.fechaCompra = fechaCompra;
       this.horaCompra = horaCompra;
       this.pagoTotal = pagoTotal;

    }
   
    
    public Integer getClave() {
        return this.clave;
    }
    
    public void setClave(Integer clave) {
        this.clave = clave;
    }
    public String getRfc() {

        return this.rfc;
    }
    
    public void setRfc(String rfc) {
        this.rfc = rfc;
    }
    public Integer getNumEmpleado() {

        return this.numEmpleado;
    }
    
    public void setNumEmpleado(Integer numEmpleado) {
        this.numEmpleado = numEmpleado;
    }
    public Integer getCodigo() {
        
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public Date getFechaCompra() {
        return this.fechaCompra;
    }
    
    public void setFechaCompra(Date fechaCompra) {
        this.fechaCompra = fechaCompra;
    }
    public Date getHoraCompra() {
        
        return this.horaCompra;
    }
    
    public void setHoraCompra(Date  horaCompra) {
        this.horaCompra = horaCompra;
    }
    public Double getPagoTotal() {
        return this.pagoTotal;
    }
    
    public void setPagoTotal(Double pagoTotal) {
        this.pagoTotal = pagoTotal;
    }




}


